import { Explainer } from '../components/Explainer';

export function LorentzPage() {
    return (
        <div>
            <div className="section-header">
                <span className="section-tag gr">Chain 1: GR</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>Lorentz from the Screen</h1>
            </div>

            <p style={{ marginBottom: '16px' }}>
                On the declared OPH paper surface, Lorentz kinematics is recovered on an explicit geometric modular
                branch. The mathematical backbone is the conformal symmetry group of the holographic screen S&sup2;.
            </p>
            <p style={{ marginBottom: '24px' }}>
                The governing identity is a classical result in mathematics:
            </p>

            <div className="math-block" style={{ fontSize: '1.1em' }}>
                Conf&#8314;(S&sup2;) = PSL(2,ℂ) ≅ SO&#8314;(3,1)
            </div>

            <p style={{ marginBottom: '16px' }}>
                The group of orientation-preserving conformal transformations of the 2-sphere is isomorphic to the
                proper orthochronous Lorentz group in 3+1 dimensions. This is imported classical mathematics. In
                OPH it supplies the ambient kinematic group available on the screen; the explicit BW branch realizes
                the corresponding action but does not derive the group identity.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>M&ouml;bius Transformations</h3>
            <p style={{ marginBottom: '8px' }}>
                A conformal map of S&sup2; (viewed as the Riemann sphere ℂ &cup; {'{'}&infin;{'}'})
                is a M&ouml;bius transformation:
            </p>
            <div className="math-block">
                z ↦ (az + b) / (cz + d), &nbsp;&nbsp; ad &minus; bc = 1
            </div>
            <p style={{ marginBottom: '16px' }}>
                where a, b, c, d &isin; ℂ. The matrix (<sup>a b</sup>/<sub>c d</sub>&rpar;
                is an element of SL(2,ℂ), and since &plusmn;I give the same transformation, the effective
                group is PSL(2,ℂ) = SL(2,ℂ)/{'{'}&plusmn;I{'}'}.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Celestial Sphere</h3>
            <p style={{ marginBottom: '16px' }}>
                An observer at a point in Minkowski spacetime sees light arriving from all directions. These
                directions form the <strong>celestial sphere</strong>. When the observer boosts, the pattern of
                light on this sphere transforms by a M&ouml;bius map. This is the aberration of starlight.
            </p>
            <p style={{ marginBottom: '16px' }}>
                Penrose recognized that the celestial sphere IS the Riemann sphere, and Lorentz boosts ARE conformal
                maps. A boost in the z-direction dilates one hemisphere and compresses the other. A rotation is
                a rigid rotation of the sphere. Together they generate the full Lorentz group.
            </p>

            <div className="card" style={{ marginBottom: '24px', borderLeft: '3px solid var(--accent-rose)' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em' }}>Key Lorentz Subgroups as Screen Actions</h4>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', fontSize: '0.85em' }}>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-rose)', fontWeight: 600, marginBottom: '4px' }}>Rotations SO(3)</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Rigid rotations of S&sup2;. Correspond to SU(2)/ℤ<sub>2</sub> &sub; PSL(2,ℂ).
                            The celestial sphere rotates.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-blue)', fontWeight: 600, marginBottom: '4px' }}>Boosts</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Dilations of the sphere about an axis. Stars bunch up in the forward direction (headlight effect).
                            Generated by z ↦ e<sup>&lambda;</sup>z.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-gold)', fontWeight: 600, marginBottom: '4px' }}>Null Rotations</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Translations on the sphere: z ↦ z + b. These correspond to Lorentz transformations
                            that leave a null direction fixed.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-green)', fontWeight: 600, marginBottom: '4px' }}>Special Conformal</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Inversions: z ↦ 1/(cz + d). Combine with translations to generate the full group.
                        </div>
                    </div>
                </div>
            </div>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>Lorentz Frames from S&sup2;</h3>
            <p style={{ marginBottom: '16px' }}>
                On the selected OPH support branch, the screen is S&sup2;. Its conformal group is the connected
                Lorentz group SO&#8314;(3,1), so this branch supplies the corresponding ambient frame kinematics.
                Independently of event height, the exact rank-three source Gram quotient defines
                W<sub>src</sub> = R &oplus; V<sub>src</sub>, the finite ambient carrier. Canonical height is used later
                only to place events in that carrier. The group correspondence is:
            </p>

            <div className="card" style={{ marginBottom: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px 16px', fontSize: '0.85em' }}>
                    <span style={{ color: 'var(--accent-cyan)' }}>Screen dimension:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>2 (the sphere S&sup2;)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Conformal group:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>PSL(2,ℂ) ≅ SO&#8314;(3,1)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Finite source carrier:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>R &oplus; rank-3 source quotient, with proved (+---) signature</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Event placement:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>F(e) = (&tau;h(e), x(e)), using canonical height and supplied spatial readback</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Why SO&#8314;(3,1)?</span>
                    <span style={{ color: 'var(--text-secondary)' }}>Because the support is S&sup2;, and Conf&#8314;(S&sup2;) ≅ SO&#8314;(3,1)</span>
                </div>
            </div>

            <p style={{ marginBottom: '16px' }}>
                If the support were S&sup1; (a circle), its corresponding conformal group would be SL(2,ℝ) ≅
                SO&#8314;(2,1). For S&sup3; it would be SO&#8314;(4,1). These group identities alone select only frame
                kinematics. OPH&apos;s four-dimensional ambient target is instead the independent direct sum of R and
                the exact rank-three source quotient. Canonical longest-parent-chain height is not part of the carrier;
                it supplies the first coordinate only when events are placed by F(e) = (&tau;h(e), x(e)). That height
                is not a physical clock, and the carrier is not an intrinsic dimension estimate for the finite poset
                or an unconditional smooth spacetime.
            </p>

            <div className="card" style={{ marginBottom: '24px', borderLeft: '3px solid var(--accent-gold)' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em', color: 'var(--accent-gold)' }}>
                    Claim boundary
                </h4>
                <p style={{ margin: '0 0 8px 0', fontSize: '0.85em' }}>
                    The screen identity Conf<sup>+</sup>(S&sup2;) ≅ SO<sup>+</sup>(3,1) is exact mathematics. The OPH claim that
                    local modular flow realizes this geometry is stated on the explicit BW branch of the scaling-limit
                    cap theory.
                </p>
                <p style={{ margin: 0, fontSize: '0.85em', color: 'var(--text-secondary)' }}>
                    The UV/BW scaffold is the realized scaling-limit cap-pair extraction plus ordered cut-pair
                    rigidity on that realized limit. Separately, authenticated read-from provenance supplies a finite
                    poset and its canonical longest-parent-chain height. Independently, the exact rank-three source
                    quotient defines the ambient carrier R &oplus; V<sub>3</sub>, with dimension four and signature
                    (+---), and each unit source direction gives a future-null vector. Height and a supplied spatial
                    readback enter only through F(e) = (&tau;h(e), x(e)). The height is an ordinal coordinate, not
                    physical event time.
                    An edge-speed bound maps generated precedence into the cone, while a converse-support certificate
                    is required for a faithful order/cone embedding.
                </p>
                <p style={{ margin: '12px 0 0 0', fontSize: '0.85em', color: 'var(--text-secondary)' }}>
                    The effective-manifold claim remains a refinement-limit statement. It needs source-selected
                    spatial placement, physical signal-cone agreement, #I / &rho; &rarr; Vol(I) calibration (where
                    #I is event count, not public capacity N), manifoldlikeness, stable dimension and topology, and
                    curvature convergence. Imposed compatibility controls do not establish that source-selected
                    refinement.
                </p>
                <p style={{ margin: '12px 0 0 0', fontSize: '0.85em', color: 'var(--text-secondary)' }}>
                    On the same finite event type, the minimal Einstein-shape theorem uses a separately supplied 3+1
                    tensor interface and nine supplied balances along exact source-unit tomography directions.
                    Symmetry plus Ward/Bianchi conservation and connectedness imply all-null balance and one constant
                    metric ambiguity. The poset does not construct the tensor fields, discrete step, or balances or
                    identify tensor-coordinate differences with the constructed source carrier. The theorem supplies
                    no identification with smooth physical curvature or stress-energy.
                </p>
            </div>

            <Explainer title="Spinors from the screen">
                <p>
                    The double cover of SO&#8314;(3,1) is SL(2,ℂ), which acts naturally on 2-component spinors.
                    Since the screen is S&sup2; = ℂP&sup1;, the fundamental screen degrees of freedom are
                    spinorial: they are 2-component complex objects (z<sub>0</sub>, z<sub>1</sub>) with z = z<sub>1</sub>/z<sub>0</sub>.
                </p>
                <p>
                    Spinors appear here as the natural coordinates of the screen. The fact that fermions are
                    spin-1/2 objects follows directly from the screen being S&sup2;.
                </p>
            </Explainer>

            <Explainer title="BMS group and asymptotic symmetries">
                <p>
                    At null infinity of an asymptotically flat spacetime, the symmetry group includes the
                    infinite-dimensional <strong>BMS group</strong>: the semi-direct product of the Lorentz group
                    with an infinite-dimensional group of supertranslations.
                </p>
                <p>
                    In OPH terms, the BMS group arises from diffeomorphisms of the screen that go beyond conformal
                    maps. These supertranslations are related to soft graviton theorems and gravitational memory
                    effects, all of which have a natural screen interpretation.
                </p>
            </Explainer>

            <Explainer title="Why a 3+1 Lorentz Module?">
                <p>
                    The OPH support is S&sup2;, whose orientation-preserving conformal group is SO&#8314;(3,1).
                    Independently of event height, R &oplus; the exact rank-three source Gram quotient gives an ambient
                    target of dimension four and signature (+---). Canonical longest-parent-chain height enters only
                    in the event placement F(e) = (&tau;h(e), x(e)). A smooth physical spacetime follows only after
                    faithful placement, physical causality, and the full refinement-limit tests.
                </p>
            </Explainer>
        </div>
    );
}
