import { Explainer } from '../components/Explainer';

export function LorentzPage() {
    return (
        <div>
            <div className="section-header">
                <span className="section-tag gr">Chain 1: GR</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>Lorentz from the Screen</h1>
            </div>

            <p style={{ marginBottom: '16px' }}>
                On the declared OPH paper surface, Lorentz kinematics is recovered on an explicit geometric modular
                branch. The mathematical backbone is the conformal symmetry group of the holographic screen S&sup2;.
            </p>
            <p style={{ marginBottom: '24px' }}>
                The governing identity is a classical result in mathematics:
            </p>

            <div className="math-block" style={{ fontSize: '1.1em' }}>
                Conf&#8314;(S&sup2;) = PSL(2,ℂ) ≅ SO&#8314;(3,1)
            </div>

            <p style={{ marginBottom: '16px' }}>
                The group of orientation-preserving conformal transformations of the 2-sphere is isomorphic to the
                proper orthochronous Lorentz group in 3+1 dimensions. This is imported classical mathematics. In
                OPH it supplies the ambient kinematic group available on the screen; the explicit BW branch realizes
                the corresponding action but does not derive the group identity.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>M&ouml;bius Transformations</h3>
            <p style={{ marginBottom: '8px' }}>
                A conformal map of S&sup2; (viewed as the Riemann sphere ℂ &cup; {'{'}&infin;{'}'})
                is a M&ouml;bius transformation:
            </p>
            <div className="math-block">
                z ↦ (az + b) / (cz + d), &nbsp;&nbsp; ad &minus; bc = 1
            </div>
            <p style={{ marginBottom: '16px' }}>
                where a, b, c, d &isin; ℂ. The matrix (<sup>a b</sup>/<sub>c d</sub>&rpar;
                is an element of SL(2,ℂ), and since &plusmn;I give the same transformation, the effective
                group is PSL(2,ℂ) = SL(2,ℂ)/{'{'}&plusmn;I{'}'}.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Celestial Sphere</h3>
            <p style={{ marginBottom: '16px' }}>
                An observer at a point in Minkowski spacetime sees light arriving from all directions. These
                directions form the <strong>celestial sphere</strong>. When the observer boosts, the pattern of
                light on this sphere transforms by a M&ouml;bius map. This is the aberration of starlight.
            </p>
            <p style={{ marginBottom: '16px' }}>
                Penrose recognized that the celestial sphere IS the Riemann sphere, and Lorentz boosts ARE conformal
                maps. A boost in the z-direction dilates one hemisphere and compresses the other. A rotation is
                a rigid rotation of the sphere. Together they generate the full Lorentz group.
            </p>

            <div className="card" style={{ marginBottom: '24px', borderLeft: '3px solid var(--accent-rose)' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em' }}>Key Lorentz Subgroups as Screen Actions</h4>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', fontSize: '0.85em' }}>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-rose)', fontWeight: 600, marginBottom: '4px' }}>Rotations SO(3)</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Rigid rotations of S&sup2;. Correspond to SU(2)/ℤ<sub>2</sub> &sub; PSL(2,ℂ).
                            The celestial sphere rotates.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-blue)', fontWeight: 600, marginBottom: '4px' }}>Boosts</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Dilations of the sphere about an axis. Stars bunch up in the forward direction (headlight effect).
                            Generated by z ↦ e<sup>&lambda;</sup>z.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-gold)', fontWeight: 600, marginBottom: '4px' }}>Null Rotations</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Translations on the sphere: z ↦ z + b. These correspond to Lorentz transformations
                            that leave a null direction fixed.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-green)', fontWeight: 600, marginBottom: '4px' }}>Special Conformal</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Inversions: z ↦ 1/(cz + d). Combine with translations to generate the full group.
                        </div>
                    </div>
                </div>
            </div>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>Lorentz Frames from S&sup2;</h3>
            <p style={{ marginBottom: '16px' }}>
                On the selected OPH support branch, the screen is S&sup2;. Its conformal group is the connected
                Lorentz group SO&#8314;(3,1), so this branch supplies the corresponding ambient frame kinematics.
                The event-base dimension is a separate question. The group correspondence is:
            </p>

            <div className="card" style={{ marginBottom: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px 16px', fontSize: '0.85em' }}>
                    <span style={{ color: 'var(--accent-cyan)' }}>Screen dimension:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>2 (the sphere S&sup2;)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Conformal group:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>PSL(2,ℂ) ≅ SO&#8314;(3,1)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Lorentz module:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>Signature (1,3) on the declared frame module</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Why SO&#8314;(3,1)?</span>
                    <span style={{ color: 'var(--text-secondary)' }}>Because the support is S&sup2;, and Conf&#8314;(S&sup2;) ≅ SO&#8314;(3,1)</span>
                </div>
            </div>

            <p style={{ marginBottom: '16px' }}>
                If the support were S&sup1; (a circle), its corresponding conformal group would be SL(2,ℝ) ≅
                SO&#8314;(2,1). For S&sup3; it would be SO&#8314;(4,1). These identities select ambient Lorentz
                modules and frame kinematics. They do not by themselves populate an event manifold or determine
                its dimension. In the OPH setup, S&sup2; therefore supplies SO&#8314;(3,1) kinematics rather than an
                unconditional 3+1-dimensional spacetime.
            </p>

            <div className="card" style={{ marginBottom: '24px', borderLeft: '3px solid var(--accent-gold)' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em', color: 'var(--accent-gold)' }}>
                    Claim boundary
                </h4>
                <p style={{ margin: '0 0 8px 0', fontSize: '0.85em' }}>
                    The screen identity Conf<sup>+</sup>(S&sup2;) ≅ SO<sup>+</sup>(3,1) is exact mathematics. The OPH claim that
                    local modular flow realizes this geometry is stated on the explicit BW branch of the scaling-limit
                    cap theory.
                </p>
                <p style={{ margin: 0, fontSize: '0.85em', color: 'var(--text-secondary)' }}>
                    The UV/BW scaffold is the realized scaling-limit cap-pair extraction plus ordered cut-pair
                    rigidity on that realized limit. A four-dimensional event manifold additionally needs the
                    E1–E6 population, separation, chart, tetrad, cone, and physical-causality receipts. The
                    source-derived read-from poset is informational; a physical causal-set reading also needs a
                    faithful embedding, manifoldlikeness, dimension, and volume correspondence. The exact
                    rank-three source-unit directions are algebraically equivalent to S&sup2; and future-null-ray
                    labels, but the d = 4 reading requires the physically faithful images of authenticated local
                    read-from links to cover those directions densely and isotropically. Count calibration separately
                    needs #I / &rho; &rarr; Vol(I), with refinement preserving
                    order, directions, and density. The same refinement must glue rank-three neighborhoods globally
                    with ~r³ carrier-ball growth; the seeded matching federation is expander-like. This soldering
                    condition belongs to the four-way join rather than adding a fifth input. Here #I is the populated
                    event count, not public-record capacity N. An imposed FCC/O<sub>h</sub> twelve-port fixture has
                    cubic carrier-ball counts matching the checked radii 0–20 and quartic fine-carrier counts matching the checked indices 1–10, with external depth supplied.
                    Its depth-20 ordering fraction near 0.10 gives a Myrheim–Meyer inversion near four, not an
                    independent dimension result. Its post-hoc profile trend reverses in an additional out-of-family
                    depth-24 extrapolation, and its depth-20 profile remains about 37 times farther from matched
                    Minkowski controls than two controls are from each other. Held-out confirmation has not been run.
                    The current federation selects neither the gluing nor the thinning, and fixed O<sub>h</sub> ports
                    are not an A<sub>5</sub>-compatible refinement family becoming dense and isotropic on S&sup2;.
                    This is no finite causet similarity and does not close the physical or continuum conditions.
                </p>
                <p style={{ margin: '12px 0 0 0', fontSize: '0.85em', color: 'var(--text-secondary)' }}>
                    The same-carrier finite Einstein-form theorem works inside a supplied 3+1 tensor interface and
                    pulls back a pre-existing coordinate-fixed nine-vector tomography frame. The informational order
                    selects neither that distinguished nine-set nor the tensor data; the nine-set is not Lorentz- or
                    SO(3)-invariant as a set; and the theorem does not infer event dimension from the poset.
                </p>
            </div>

            <Explainer title="Spinors from the screen">
                <p>
                    The double cover of SO&#8314;(3,1) is SL(2,ℂ), which acts naturally on 2-component spinors.
                    Since the screen is S&sup2; = ℂP&sup1;, the fundamental screen degrees of freedom are
                    spinorial: they are 2-component complex objects (z<sub>0</sub>, z<sub>1</sub>) with z = z<sub>1</sub>/z<sub>0</sub>.
                </p>
                <p>
                    Spinors appear here as the natural coordinates of the screen. The fact that fermions are
                    spin-1/2 objects follows directly from the screen being S&sup2;.
                </p>
            </Explainer>

            <Explainer title="BMS group and asymptotic symmetries">
                <p>
                    At null infinity of an asymptotically flat spacetime, the symmetry group includes the
                    infinite-dimensional <strong>BMS group</strong>: the semi-direct product of the Lorentz group
                    with an infinite-dimensional group of supertranslations.
                </p>
                <p>
                    In OPH terms, the BMS group arises from diffeomorphisms of the screen that go beyond conformal
                    maps. These supertranslations are related to soft graviton theorems and gravitational memory
                    effects, all of which have a natural screen interpretation.
                </p>
            </Explainer>

            <Explainer title="Why a 3+1 Lorentz Module?">
                <p>
                    The OPH support is S&sup2;, whose orientation-preserving conformal group is SO&#8314;(3,1).
                    This fixes the Lorentz group acting on the declared four-coordinate module and the H&sup3;
                    observer-frame fiber. It does not prove that the event base is a four-dimensional spacetime;
                    that conclusion is conditional on the separate event-manifold and physical-causality receipts.
                </p>
            </Explainer>
        </div>
    );
}
